
version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system_monitor_bot
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./system_monitor_bot.db:/app/system_monitor_bot.db
      - C:\:/host_c # For Windows host, adjust if on Linux/macOS
    restart: unless-stopped
    command: python monitor.py
