services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system_monitor_bot
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./system_monitor_bot.db:/app/system_monitor_bot.db
    restart: unless-stopped
    command: python monitor.py
